
services:

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  # migrate:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.migrate
  #   depends_on:
  #     - db
  #   env_file:
  #     - .env
  #   restart: "no"

    
  # app:
  #   build: .
  #   container_name: sveltekit_app
  #   ports:
  #     - "5173:5173"
  #   env_file:
  #     - .env
  #   depends_on:
  #     - db
  #   restart: unless-stopped